//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMI_Calculator_SOC_Application.BMI_Service_Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BMI_Service_Reference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/calculateBMI", ReplyAction="http://tempuri.org/IService1/calculateBMIResponse")]
        int calculateBMI(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/calculateBMI", ReplyAction="http://tempuri.org/IService1/calculateBMIResponse")]
        System.Threading.Tasks.Task<int> calculateBMIAsync(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getHealthIndicator", ReplyAction="http://tempuri.org/IService1/getHealthIndicatorResponse")]
        string getHealthIndicator(int BMI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getHealthIndicator", ReplyAction="http://tempuri.org/IService1/getHealthIndicatorResponse")]
        System.Threading.Tasks.Task<string> getHealthIndicatorAsync(int BMI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BMI_Calculator_SOC_Application.BMI_Service_Reference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BMI_Calculator_SOC_Application.BMI_Service_Reference.IService1>, BMI_Calculator_SOC_Application.BMI_Service_Reference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int calculateBMI(int height, int weight) {
            return base.Channel.calculateBMI(height, weight);
        }
        
        public System.Threading.Tasks.Task<int> calculateBMIAsync(int height, int weight) {
            return base.Channel.calculateBMIAsync(height, weight);
        }
        
        public string getHealthIndicator(int BMI) {
            return base.Channel.getHealthIndicator(BMI);
        }
        
        public System.Threading.Tasks.Task<string> getHealthIndicatorAsync(int BMI) {
            return base.Channel.getHealthIndicatorAsync(BMI);
        }
    }
}
