//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMI_Calculator_Application_REST.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/calculateBMI", ReplyAction="http://tempuri.org/IService/calculateBMIResponse")]
        int calculateBMI(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/calculateBMI", ReplyAction="http://tempuri.org/IService/calculateBMIResponse")]
        System.Threading.Tasks.Task<int> calculateBMIAsync(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getHealthIndicator", ReplyAction="http://tempuri.org/IService/getHealthIndicatorResponse")]
        string getHealthIndicator(int BMI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getHealthIndicator", ReplyAction="http://tempuri.org/IService/getHealthIndicatorResponse")]
        System.Threading.Tasks.Task<string> getHealthIndicatorAsync(int BMI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : BMI_Calculator_Application_REST.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<BMI_Calculator_Application_REST.ServiceReference1.IService>, BMI_Calculator_Application_REST.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int calculateBMI(int height, int weight) {
            return base.Channel.calculateBMI(height, weight);
        }
        
        public System.Threading.Tasks.Task<int> calculateBMIAsync(int height, int weight) {
            return base.Channel.calculateBMIAsync(height, weight);
        }
        
        public string getHealthIndicator(int BMI) {
            return base.Channel.getHealthIndicator(BMI);
        }
        
        public System.Threading.Tasks.Task<string> getHealthIndicatorAsync(int BMI) {
            return base.Channel.getHealthIndicatorAsync(BMI);
        }
    }
}
